# Site settings
title: blog.sebastianschasse.de
email: blog@sebastianschasse.de
description: > # this means to ignore newlines until "baseurl:"
  This is another blog of a software developer and computer science student.
  baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blog.sebastianschasse.de" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  schasse

# Build settings
markdown: kramdown
